workflows:
  ios-debug:
    name: iOS Debug Build
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - supabase_credentials
    cache:
      cache_paths:
        - ~/.pub-cache
        - $CM_BUILD_DIR/ios/Pods
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Setup Environment
        script: |
          echo "SUPABASE_URL=${SUPABASE_URL}" > .env
          echo "SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}" >> .env
      - name: Install Dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Install Pods
        script: |
          cd ios
          pod install --repo-update
          cd ..
      - name: Analyze Code
        script: flutter analyze --no-pub
      - name: Build iOS Debug
        script: flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphonesimulator/*.app
    publishing:
      email:
        recipients:
          - ${CM_EMAIL}
        notify:
          success: true
          failure: true

  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.imagineaccess.app
      groups:
        - supabase_credentials
    cache:
      cache_paths:
        - ~/.pub-cache
        - $CM_BUILD_DIR/ios/Pods
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Setup Environment
        script: |
          echo "SUPABASE_URL=${SUPABASE_URL}" > .env
          echo "SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}" >> .env
      - name: Install Dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Install Pods
        script: |
          cd ios
          pod install --repo-update
          cd ..
      - name: Build IPA
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - ${CM_EMAIL}
        notify:
          success: true
        failure: true
